In [100]:
import pandas as pd
import numpy as np

In [101]:
pd.set_option('display.max_rows',None)
pd.set_option('display.max_columns',None)

In [102]:
df1 = pd.read_csv('flat_cleaned.csv')
df2 = pd.read_csv('house_cleaned.csv')

In [103]:
df1 = df1.rename(columns={'area':'area_in_sqft'})

In [104]:
df1.columns

Index(['society', 'price_in_crore', 'price_per_sqft', 'areaWithType',
       'bedRoom', 'bathroom', 'balcony', 'additionalRoom', 'address',
       'floorNum', 'facing', 'agePossession', 'nearbyLocations', 'description',
       'furnishDetails', 'features', 'rating', 'bhk', 'property_type',
       'location', 'area_in_sqft', 'totalFloor'],
      dtype='object')

In [105]:
df1 = df1[['society', 'price_in_crore', 'price_per_sqft', 'areaWithType',
       'bedRoom', 'bathroom', 'balcony', 'additionalRoom', 'address',
       'floorNum', 'facing', 'agePossession', 'nearbyLocations', 'description',
       'furnishDetails', 'features', 'rating', 'property_type',
       'location', 'area_in_sqft', 'totalFloor', 'bhk']]

In [106]:
df1.head(1)

,society,price_in_crore,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_type,location,area_in_sqft,totalFloor,bhk
0,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ...",flat,sector 7,900.0,4,2

In [107]:
df2.head(1)

,society,price_in_crore,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_type,location,area_in_sqft
0,Bptp Visionnaire,5.24,20115.0,Plot area 290(242.48 sq.m.),5,5,3+,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5...",House,Sector 70A Gurgaon,2604.89

In [108]:
df = pd.concat([df1,df2],ignore_index=True)

In [109]:
df.shape

(4026, 22)

In [110]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4026 entries, 0 to 4025
Data columns (total 22 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   society          3440 non-null   object
 1   price_in_crore   3986 non-null   float64
 2   price_per_sqft   3986 non-null   float64
 3   areaWithType     3969 non-null   object
 4   bedRoom          4026 non-null   int64
 5   bathroom         4026 non-null   int64
 6   balcony          4026 non-null   object
 7   additionalRoom   4026 non-null   object
 8   address          4007 non-null   object
 9   floorNum         4026 non-null   int64
 10  facing           2785 non-null   object
 11  agePossession    3968 non-null   object
 12  nearbyLocations  3806 non-null   object
 13  description      4018 non-null   object
 14  furnishDetails   2930 non-null   object
 15  features         3252 non-null   object
 16  rating           3561 non-null   object
 17  property_type    4026 non-null   object
 18  location         4026 non-null   object
 19  area_in_sqft     4025 non-null   float64
 20  totalFloor       2995 non-null   float64
 21  bhk              2995 non-null   float64
dtypes: float64(5), int64(3), object(14)
memory usage: 692.1+ KB

In [111]:
df.isnull().sum()

society             586
price_in_crore       40
price_per_sqft       40
areaWithType         57
bedRoom               0
bathroom              0
balcony               0
additionalRoom        0
address              19
floorNum              0
facing             1241
agePossession        58
nearbyLocations     220
description           8
furnishDetails     1096
features            774
rating              465
property_type         0
location              0
area_in_sqft          1
totalFloor         1031
bhk                1031
dtype: int64

In [112]:
# df['agePossession'] = df['agePossession'].fillna('undefined')

In [121]:
# df = df.drop(18).reset_index(drop=True)

In [125]:
# df[df['description'].isnull()]

In [126]:
# df[df['description'].isnull()].index

In [127]:
# df = df.drop([3312, 3313, 3314, 3315, 3318, 3319, 3320, 3828]).reset_index(drop=True)

In [128]:
# df['bhk'] = df['bhk'].fillna('No bkh')

In [134]:
# df['totalFloor'] = df['totalFloor'].fillna('NA')

In [135]:
# df['features'] = df['features'].fillna('NA')

In [136]:
# df['facing'] = df['facing'].fillna('NA')

In [137]:
# df['address'] = df['address'].fillna('NA')

In [85]:
# df[df['price_in_crore'].isnull()].isnull().sum()

In [86]:
# df[df['price_per_sqft'].isnull()].isnull().sum()

In [87]:
# df[df['areaWithType'].isnull()].isnull().sum()

In [140]:
# df[df['price_in_crore'].isnull()].index

In [141]:
# df  = df.drop([3040, 3081, 3082, 3097, 3098, 3108, 3243, 3253, 3254, 3266, 3270, 3271,
#        3277, 3283, 3284, 3292, 3341, 3357, 3370, 3422, 3430, 3433, 3448, 3508,
#        3534, 3570, 3607, 3717, 3725, 3754, 3769, 3777, 3794, 3817, 3892, 3975,
#        3995, 3996]).reset_index(drop=True)

In [143]:
# df['society'] = df['society'].fillna('independent')

In [144]:
df[df['areaWithType'].isnull()].isnull().sum()

society             0
price_in_crore      6
price_per_sqft      6
areaWithType       44
bedRoom             0
bathroom            0
balcony             0
additionalRoom      0
address             0
floorNum            0
facing              0
agePossession      44
nearbyLocations     0
description         0
furnishDetails     44
features            0
rating              6
property_type       0
location            0
area_in_sqft        0
totalFloor          0
bhk                 0
dtype: int64

In [145]:
df.to_csv('cleaned_v1.csv',index=False)